=== CortexVacua/MTDFramework/Framework/config-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "AttackTypes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Type": {
            "type": "string"
          },
          "MTDSolutions": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "Priority": {
                  "type": "integer"
                },
                "ScriptName": {
                  "type": "string"
                },
                "AbsolutePath": {
                  "type": "string"
                },
                "RunWithPrefix": {
                  "type": "string"
                },
                "Params": {
                  "type": "string"
                }
              },
              "required": [
                "Priority",
                "ScriptName",
                "AbsolutePath",
                "RunWithPrefix"
              ]
            }
          },
          "DeploymentPolicy": {
            "type": "object",
            "properties": {
              "ScriptName": {
                "type": "string"
              },
              "AbsolutePath": {
                "type": "string"
              },
              "RunWithPrefix": {
                "type": "string"
              }
            },
            "required": [
              "ScriptName",
              "AbsolutePath",
              "RunWithPrefix"
            ]
          }
        },
        "required": [
          "Type",
          "MTDSolutions"
        ]
      }
    },
    "AllowAllExternalReports": {
      "type": "boolean"
    },
    "WhiteListForExternalReports": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "PortToUse": {
      "type": "integer"
    }
  },
  "required": [
    "AttackTypes",
    "AllowAllExternalReports",
    "WhiteListForExternalReports",
    "PortToUse"
  ]
}

=== CortexVacua/MTDFramework/Framework/config.json
{
  "AttackTypes": [
    {
      "Type": "CnC",
      "MTDSolutions": [
        {
          "Priority": 1,
          "ScriptName": "ChangeIpAddress.py",
          "AbsolutePath": "/opt/MTDFramework/CnC/",
          "RunWithPrefix": "python3"
        }
      ]
    },
    {
      "Type": "Rootkit",
      "MTDSolutions": [
        {
          "Priority": 1,
          "ScriptName": "RemoveRootkit.py",
          "AbsolutePath": "/opt/MTDFramework/Rootkit/",
          "RunWithPrefix": "python3"
        }
      ]
    },
    {
      "Type": "Ransomware",
      "MTDSolutions": [
        {
          "Priority": 1,
          "ScriptName": "CreateDummyFiles.py",
          "AbsolutePath": "/opt/MTDFramework/Ransomware/",
          "RunWithPrefix": "python3",
          "Params": "--path /home/ --numberOfDummyFiles 30 --numberOfDummyFilesPerSubdirectory 15 --size 10 --extension pdf"
        },
        {
          "Priority": 2,
          "ScriptName": "ChangeFileTypes.py",
          "AbsolutePath": "/opt/MTDFramework/Ransomware/",
          "RunWithPrefix": "python3",
          "Params": "--path /home/ --extensions pdf png so docx --recursive"
        }

      ]
    }
  ],
  "AllowAllExternalReports": false,
  "WhiteListForExternalReports": [],
  "PortToUse": 1234
}
